pgaskin/NickelMenu

- src/failsafe.c
Fix #17
Also gave it a name while I was there ;).
> Ensure the failsafe thread is a detached one

- res/doc
- src/action_cc.cc
> Implement quiet option for cmd_output

- src/kfmon.c
- src/kfmon.h
That's been nagging me for a while, so, eh ;p.
> Minor cosmetic tweaks to the KFMon list code

- .gitignore
- Makefile
- res/doc
- src/config.c
- src/config.h
- src/generator.c
- src/generator.h
- src/generator_c.c
- src/init.c
- src/util.h
> Implement menu item generators

- src/config.c
> Ignore special files during config parsing

- res/doc
- src/config.c
> Rename chain to chain_success

- res/doc
- src/action.h
- src/action_c.c
- src/menu.cc
> Implement skip action

- res/doc
- src/action.h
- src/action_cc.cc
> Implement nickel_open action

- res/doc
- src/action_cc.cc
> Implement nickel_misc:home action

- res/doc
- src/action.h
- src/action_cc.cc
> Implement nickel_wifi action

- src/menu.cc
> Better menu item injection

- res/doc
- src/action_cc.cc
> Switch to new method for nickel_extras:web_browser and implement url/css options

- res/doc
- src/action_cc.cc
> Implement option to set values for nickel_setting:* explicitly

- src/config.c
- src/config.h
- src/generator.c
- src/generator.h
- src/generator_c.c
- src/init.c
> Implement generator updates

- res/doc
- src/action.h
- src/action_cc.cc
> Improve extensibility of nickel_setting, split browser stuff into nickel_browser action

- res/doc
- src/config.c
- src/config.h
- src/nickelmenu.cc
> Implement browser menu location

- res/doc
- src/config.c
- src/config.h
- src/nickelmenu.cc
> Implement library menu location

- res/doc
- src/action_cc.cc
> Implement auto_usb_gadget for nickel_setting

- res/doc
- src/action_cc.cc
Also removed library2 from docs.
Part of #81, needed for #79.
> Made nickel_open:library:library identical to library2

- README.md
- res/doc
- src/nickelmenu.cc
> Add hook to add a main menu button to the bottom tab bar in 4.23.15505+

- src/action_cc.cc
> Remove deprecated nickel_open:library:library2 action

- res/doc
- src/config.c
- src/config.h
> Implement experimental options

- res/doc
- src/nickelmenu.cc
> Implement experiemental:main_menu_15505_label option

- src/nickelmenu.cc
> Decode result messages as utf-8 instead of latin-1

- res/doc
- src/nickelmenu.cc
- src/nickelmenu.h
> Implement selection menu location

- .github/workflows/build.yaml
- .github/workflows/release.yaml
- .github/workflows/test.yaml
make actions runnable by updating to still supported versions
> raise actions to latest versions
