res/doc

Probably easier than to ask users to run it in a shell, or rely on
devmode's logging.

Add an example spawn_cmd that dumps the syslog to onboard

---

Makefile

(Not that we need it w/ the current TC ;)).
Honor CXXFLAGS when linking. This is necessary when using LTO with such
and ancient GCC version.

Honor CPPFLAGS

---

src/action_cc.cc
src/config.c
src/util.h

Fix #16
(Mildly tested, feel free to try to break it ;)).

Allow whitespace in cmd_spawn/cmd_output args

---

res/doc
src/config.c
src/menu.cc
src/menu.h

Implement conditional actions

---

Makefile
src/init.c
src/util.h

Might come in handy one day, because I know quite a few people extremely averse to updating stuff ^^.
e.g.,
```
May 13 17:57:13 nickel: (NickelMenu) version: v0.0.3-2-g043dfb3 (src/init.c:24)
May 13 17:57:13 nickel: (NickelMenu) init: creating failsafe (src/init.c:25)
```

Log the exact version at init

---

res/doc
src/action.h
src/action_c.c
src/generator.h
src/generator_c.c
src/kfmon.c
src/kfmon.h
src/kfmon_helpers.h

Implement a KFMon generator

---

.drone.yml
Makefile
src/config.c
src/config.h
src/init.c

This option allows NickelMenu to be uninstalled by deleting the config dir.
Closes #34

Implement NM_UNINSTALL_CONFIGDIR build option

---

src/util.h

It's almost too small a change to bother with a PR, but I wanted to make sure others were happy with the approach I took.
Basically, it sets the library name in `NM_LOG` as a macro, allowing the name to be overridden as a CFLAG if desired. If the macro `NM_LOG_NAME` isn't defined, it defaults to `"NickelMenu".
This allows reusing the logging code in other libraries without having to change any headers or redefine macros.

Use macro for setting library name in log

---

src/config.c
src/config.h
src/failsafe.c
src/init.c
src/init.h
src/menu.cc
src/menu.h

This PR implements config file reloading.
Every time the menu is opened, the config files are scanned. If the number of files or the modification time of one changes, they are re-parsed and re-generated. If there is a config error or I/O error while parsing or scanning the files, an item is added showing it like usual. If there aren't any config entries, the usual one referring to the documentation is shown.
There should not be any noticeable delay in opening the menu, except around another 200ms (up to 500ms) when opening it after a config change.
closes #42
---
For the config parser improvements, see https://github.com/geek1011/NickelMenu/pull/47#issuecomment-646444323.
closes #48

Implement config file reloading and improve the config parser

---

src/init.c
src/init.h
src/menu.cc

Instead of returning a bool from `nm_global_config_update` indicating whether the menu items were modified, return an int indicating the current config revision which can then be compared against one stored as a property of the menu.
closes #57

Fix reloaded config only propagating to new menus or the first existing one

---

src/init.c

It hasn't been used except for before the initial release, and it's more likely to cause odd issues when parts of NM are reused by other mods.

Remove support for loading using LD_PRELOAD

---

res/doc
src/action.h
src/action_cc.cc

Implement nickel_orientation action

---

res/doc
src/action_cc.cc
test/syms/main.go

The navigation changes in 4.23.15505 caused a few actions to break.
closes #79

Update actions for compatibility with 4.23.15505

---

src/action_cc.cc
src/nickelmenu.cc

ConfirmationDialog uses Qt::RichText for the body text, which causes line breaks to be collapsed since the text is rendered as HTML. This can be fixed by using Qt::convertFromPlainText with Qt::WhiteSpacePre.
fixes #92

Fix cmd_output newlines not being displayed

---

src/config.c

This fixes a regression in ee0eb7ccf735ad26593cb5a4804b746e273469b4 (#47) which caused vague error messages to be returned instead of specific error messages from `nm_config_parse__line_*`. These functions should have returned `true` on error, but were returning `NULL` (i.e. `false`) instead, causing `nm_config_parse` to treat it as an unknown line type instead of returning the specific issue with the line. This regression does not cause any issues other than vague error messages being returned for certain errors during config parsing.
In addition, this fixes another regression discovered by @NiLuJe where configuration errors would persist in rare situations due to `nm_config_files` not clearing existing errors as expected. This issue does not happen if the config error menu item is …

Fix error handling regressions in config parser

---

res/doc
src/nickelmenu.cc

Implement experimental option for custom main menu icon on 4.23.15505+

---

src/action_cc.cc

This PR fixes #107 
The previous code simply passed `nullptr` to the `MoreController::dropbox` method, instead of a pointer to a valid 'this' pointer. The  new code creates a valid `MoreController` object to pass to the `dropbox` method.
Tested on my Forma with fw 4.26.16704.
@NiLuJe can you please double check it works on your Forma?
Has anyone got fw 4.23.15505 they could test with? It should work, but probably wouldn't hurt to test...

Fix Dropbox on FW 4.26.16704

---

src/action_cc.cc

Minor typo that came up when people tried to use the `dark_mode` option on current release builds ;).
c.f., https://www.mobileread.com/forums/showpost.php?p=4148920&postcount=33

nickel_setting: Print the correct argument on error

---

res/doc
src/action.h
src/action_cc.cc

Implementation of a new action "nickel_bluetooth" to turn Bluetooth on and off via NickelMenu.
Available commands are:
enable
disable
toggle
I've been testing/using this modified version of NickelMenu on my Clara 2E and It should be compatible with all Bluetooth devices. 
This should address issue  #142 
Usage examples:
menu_item :main  :Bluetooth (enable)      :nickel_bluetooth     :enable
menu_item :main  :Bluetooth (disable)     :nickel_bluetooth     :disable
menu_item :main  :Bluetooth (toggle)      :nickel_bluetooth     :toggle

Implement nickel_bluetooth action

---

res/doc
src/nickelmenu.cc

Add a config to disable the main menu button

---

res/doc
src/nickelmenu.cc

I got annoyed by the useless notebooks button, so I added a way to remove or configure the label/icons on the builtin menu items.
This config:
```
menu_item :library    :KOReader           :cmd_spawn          :quiet:exec /mnt/onboard/.adds/koreader/koreader.sh
experimental:menu_main_15505_enabled:0
experimental:menu_main_15505_0_enabled:0
experimental:menu_main_15505_1_label:Books
experimental:menu_main_15505_2_enabled:1
experimental:menu_main_15505_3_enabled:0
experimental:menu_main_15505_default:1
```
results in this:
(The Home button is removed, but you'll still spawn in there on initial boot: it'd be nice to be able to specify a default, but I'm not entirely sure what the best way of doing so is. Injecting click events in qt seems a lot less trivial than I would expect...)

Allow configuration of builtin main menu buttons

---

res/doc

Hi,
the documentation on the main menu had me confused. First commit is a typo that should be fixed imo, second one is trying to make it more clear that those whole strings are not the values but explaining  values to be set.
Thanks !

Fix documentation for main menu options
